# Generated by Django 5.0.6 on 2024-12-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='profile',
        ),
    ]
