# Generated by Django 5.0.6 on 2024-12-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect1', '0002_remove_userdetails_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile',
            field=models.ImageField(default='xxx', upload_to='profiles/'),
        ),
    ]
