# Generated by Django 5.0.6 on 2024-10-31 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('team_color', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='people_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=25)),
                ('team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
            options={
                'db_table': 'people_details',
            },
        ),
    ]
