# Generated by Django 5.0.6 on 2024-10-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=25)),
            ],
            options={
                'db_table': 'people_details',
            },
        ),
    ]
